rules:
  -
    - !ruby/regexp '/\.html$/'
    -
      - !ruby/regexp '/^cr|none$/'
      - !ruby/regexp '/^true$/'
  -
    - !ruby/regexp '/[\.-]min\./'
    -
      - !ruby/regexp '/^none$/'
      - !ruby/regexp '/^false$/'
  -
    - !ruby/regexp '/\.(reg|bat|ps1|cs|fs|xaml|csproj|sln)$/'
    -
      - !ruby/regexp '/^crlf|none$/'
      - !ruby/regexp '/^true|false$/'
  -
    - !ruby/regexp '/.*/'
    -
      - !ruby/regexp '/^lf|none$/'
      - !ruby/regexp '/^true$/'
